local gpu = require("component").gpu
local file = io.open("colorCodes.lua", "w")
file:write(" -- File generated by ./_savePaletteColors.lua\n",
           "local colors = require(\"colors\")\n",
           "local color_table = {\n")
for i = 0, 15 do
  file:write("  ", string.format("%x", gpu.getPaletteColor(i)), ",\n")
end
file:write("for i = 0, 15 do\n",
           "  color_table[colors[i]] = color_table[i]\n",
           "end\n",
           "return color_table")