 -- File generated by ./_savePaletteColors.lua
local colors = require("colors")
local color_table = {
  0xffffff, --  white
  0xffcc33, --  orange
  0xcc66cc, --  magenta
  0x6699ff, --  lightblue
  0xffff33, --  yellow
  0x33cc33, --  lime
  0xff6699, --  pink
  0x333333, --  gray
  0xcccccc, --  silver
  0x336699, --  cyan
  0x9933cc, --  purple
  0x333399, --  blue
  0x663300, --  brown
  0x336600, --  green
  0xff3333, --  red
  0x000000, --  black
}
for i = 0, 15 do
  color_table[colors[i]] = color_table[i]
end
return color_table